[sidebar]
The 2026 Nodes Implementation Plan has been prepared by the https://www.gbif.org/contact-us/directory?group=nsg[Nodes Steering Group^] and Secretariat in December 2025 and approved in January 2026. It is an update to the https://docs.gbif.org/nodes-implementation-2025/en/[2025 Nodes Implementation Plan^] and aligns with https://www.gbif.org/document/50lI7Bxn2p1vRgpbs7aXaT/[GBIF Strategic Framework 2023-2027^]. It provides a framework for discussions at the Regional Nodes Meetings.

== Rationale

Since the 15th Global Nodes Meeting (October 2019 at GB26 in Leiden), the Nodes Committee, led by the Nodes Steering Group (NSG), has identified priority objectives to guide the global efforts of the nodes.

These strategic objectives are implemented by the Nodes Committee with the support of the Secretariat under the supervision of the NSG. They also provide a framework for discussions at the Global Nodes Meetings and Regional Nodes Meetings. At the end of the year, the NSG will assess the progress towards these strategic objectives.

The global objectives are aligned with GBIF’s strategic framework. Regions are welcome to add their own objectives. Different regions and Participants might have different approaches and activities to reach the common strategic objectives. For this reason, the activities under each objective should be considered as a non-exhaustive list of suggestions that might differ regionally.

== The strategic objectives

. Engage research communities for data mobilization and use
. Support national and regional biodiversity commitments and the science-policy interface
. Promote open biodiversity data approaches within the business and finance sectors
. Support node development through knowledge sharing and mobility of skills
. Develop capacity within regional communities of practice
. Contribute to data model enhancements
