https://docs.gbif.org/documentation-guidelines/[image:https://docs.gbif.org/documentation-guidelines/gbif-document-shield.svg[GBIF Document]]
// DOI badge: If you have a DOI, remove the comment ("// ") from the line below, change "10.EXAMPLE/EXAMPLE" to the DOI in all three places, and remove this line.
https://doi.org/10.35035/9m1k-yh45[image:https://zenodo.org/badge/DOI/10.35035/9m1k-yh45.svg[doi:10.35035/9m1k-yh45]]
// License badge
https://creativecommons.org/licenses/by-sa/4.0/[image:https://img.shields.io/badge/License-CC%20BY%2D-SA%204.0-lightgrey.svg[CC BY-SA 4.0]]
// Build status badge: In the text below, please update "doc-template" to "doc-your-document-name", and remove this line.
https://builds.gbif.org/job/doc-template/lastBuild/console[image:https://builds.gbif.org/job/doc-template/badge/icon[Build status]]

= GBIF Nodes Implementation Plan 2026

This document has been prepared with the Nodes Steering Group in December 2025 and approved in January 2026. They align with the GBIF strategic framework 2023-2027 and also provide a framework for discussions at the Global Nodes Meetings and Regional Nodes Meetings. The document also includes an appendix detailing specific plans of individual nodes for 2026.

The document is available as HTML and PDF at https://docs.gbif.org/nodes-implementation-2026/en/[GBIF Nodes Implementation Plan 2026^].

The document is built using AsciiDoc, for guidance on how to make changes or suggestions see the https://docs.gbif.org/documentation-guidelines/[GBIF Documentation Guidelines^].
